### ISSUE TITLE
CAVF and Formula 3 

### ISSUE THREAD

**Issue by ydhexyk** [MartinBraquet/vector-field-obstacle-avoidance#2]
Hello author, I would like to ask about the concept of (CAVF) in the article. Could you please specify which article first introduced this concept? Is Formula 3 the definition proposed in this article, or is it referenced from another article? I apologize for the disturbance, but I am eager to study this article in detail. However, there are some basic concepts that I am not very familiar with. Could you please recommend some learning materials or literature? I truly appreciate your help.

**Comment by MartinBraquet** [comment]
Hi @ydhexyk , 

> Could you please specify which article first introduced this concept?

Vector fields have been introduced decades ago. This paper is one of the first, if not the first, to introduce it:

_O. Khatib, "Real-time obstacle avoidance for manipulators and mobile robots," Proceedings. 1985 IEEE International Conference on Robotics and Automation, St. Louis, MO, USA, 1985, pp. 500-505, doi: 10.1109/ROBOT.1985.1087247._

> Is Formula 3 the definition proposed in this article, or is it referenced from another article?

Formula 3 is proposed in this article.

**Comment by ydhexyk** [comment]
Thank you very much for your response; I truly appreciate it.

**Comment by ydhexyk** [comment]
@MartinBraquet Respected author，I would like to ask why  obstacle avoidance field ho and a destination steering field hf are defined in this way. Was it optimized or improved from some original formula? thank you

**Comment by MartinBraquet** [comment]
Hi @ydhexyk , it was not significantly inspired by any other formula. It is the simplest formula that I could find which respects the impenetrability condition under a double integrator dynamics. The design of gamma and R have some similarities with the vector field designed in this paper:
```
[Collision Avoidance for an Unmanned Aerial Vehicle in the Presence of Static and Moving Obstacles](https://arc.aiaa.org/doi/abs/10.2514/1.G004446)
Andrei Marchidan and Efstathios Bakolas
Journal of Guidance, Control, and Dynamics 2020 43:1, 96-110
```

**Comment by ydhexyk** [comment]
Thank you very much for your response. It has been extremely beneficial, and I now realize that there is much more for me to learn. I truly appreciate your assistance.
